name = "Compose"
license = "MIT"
licenselink = "https://github.com/google/compose/blob/master/LICENSE"
description = "A Hugo theme for technical documentation sites"
homepage = "https://compose-docs.netlify.com"
tags = ["documentation", "simple", "customizable", "docs"]
features = ["docs", "search"]
min_version = 0.61

[author]
  name = "Weru"
  homepage = "https://compose-docs.netlify.com"
