name = "Compose"
license = "MIT"
licenselink = "https://github.com/onweru/compose/blob/master/LICENSE"
description = "A hugo docs theme inspired by forestry.io's docs page"
homepage = "https://compose-docs.netlify.com"
tags = ["simple", "docs"]
features = ["docs", "search"]
min_version = 0.61

[author]
  name = "Weru"
  homepage = "https://github.com/onweru"
